### ISSUE TITLE
Flux not loading

### ISSUE THREAD

**Issue by FabulousTiger** [ai-dock/stable-diffusion-webui-forge#2]
I can't seem to get flux to load and I also don't see the forge related ui changes like memory weights. Feels like it has not build the forge ui it has merged them or something. I used the provisioning flux script and the models and vae is there but can't get it to load. 
Here is when I try to load the model.
```setting sd_model_checkpoint to flux1-dev.safetensors [4610115bb0]: KeyError
Traceback (most recent call last):
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/options.py", line 165, in set
    option.onchange()
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/initialize_util.py", line 174, in
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/sd_models.py", line 629, in reload_model_weights
    return load_model(info)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/sd_models.py", line 586, in load_model
    sd_model = forge_loader.load_model_for_a1111(timer=timer, checkpoint_info=checkpoint_info, state_dict=state_dict)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules_forge/forge_loader.py", line 152, in load_model_for_a1111
    forge_objects = load_checkpoint_guess_config(
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules_forge/forge_loader.py", line 90, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/ldm_patched/modules/model_detection.py", line 163, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/ldm_patched/modules/model_detection.py", line 49, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'
root@ai-dock:/# logtail.sh
```
Here is when I try to load the vae.

```changing setting sd_vae to ae.safetensors: AttributeError
Traceback (most recent call last):
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/options.py", line 165, in set
    option.onchange()
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/initialize_util.py", line 175, in
    shared.opts.onchange("sd_vae", wrap_queued_call(lambda: sd_vae.reload_vae_weights()), call=False)
  File "/mnt/hydra-media/home/ai-dock/stable-diffusion-webui-forge/modules/sd_vae.py", line 254, in reload_vae_weights
    checkpoint_info = sd_model.sd_checkpoint_info
AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'```

**Comment by robballantyne** [comment]
@FabulousTiger I need to update docker-compose.yaml 

Please use image `aidockorg/stable-diffusion-webui-forge-cuda:latest`

**Comment by FabulousTiger** [comment]
Thanks will switch and try it out. 👍
