### ISSUE TITLE
Launch Error? Missing xtransformers

### ISSUE THREAD

**Issue by jasonmbrown** [ai-dock/stable-diffusion-webui-forge#8]
ModuleNotFoundError: import of xformers halted; None in sys.modules

Device: cuda:0 Tesla P40 : native
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/opt/stable-diffusion-webui-forge/launch.py", line 48, in <module>
    main()
  File "/opt/stable-diffusion-webui-forge/launch.py", line 44, in main
    start()
  File "/opt/stable-diffusion-webui-forge/modules/launch_utils.py", line 508, in start
    import webui
  File "/opt/stable-diffusion-webui-forge/webui.py", line 17, in <module>
    initialize.imports()
  File "/opt/stable-diffusion-webui-forge/modules/initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/opt/stable-diffusion-webui-forge/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/opt/stable-diffusion-webui-forge/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/opt/stable-diffusion-webui-forge/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/opt/stable-diffusion-webui-forge/modules/hypernetworks/hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "/opt/stable-diffusion-webui-forge/modules/sd_models.py", line 21, in <module>
    from modules_forge import forge_loader
  File "/opt/stable-diffusion-webui-forge/modules_forge/forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "/opt/stable-diffusion-webui-forge/ldm_patched/modules/model_detection.py", line 1, in <module>
    import ldm_patched.modules.supported_models
  File "/opt/stable-diffusion-webui-forge/ldm_patched/modules/supported_models.py", line 2, in <module>
    from . import model_base
  File "/opt/stable-diffusion-webui-forge/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/opt/stable-diffusion-webui-forge/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/opt/stable-diffusion-webui-forge/ldm_patched/ldm/modules/attention.py", line 14, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules
2024-10-05 02:46:14,689 INFO exited: forge (exit status 1; not expected)

Just wondering if anyone knows how to fix this issue?

Edit: I fixed it by adding --xformers

**Comment by s-KaiNet** [comment]
Could you tell where to add `--xformers`? Basically having the same problem.

**Comment by s-KaiNet** [comment]
**UPD**: Added `COMMANDLINE_ARGS=--xformers` to env. vars and it also worked for me.

**Comment by gltai06** [comment]
In which file should I add the "--xformers" parameter?
