### ISSUE TITLE
buggy extension installation keeps forge from starting

### ISSUE THREAD

**Issue by gitwittidbit** [ai-dock/stable-diffusion-webui-forge#9]
First of all, thank you for your work - this is the only forge installation I got to work.

After initially successfully installing forge, I went and installed a couple of extension through the GUI. The way I understand, they don't get installed immediately but only when the server restarts.

Now when I (re)start the container, forge tries to install the extension and then throws this error:

`*** Error running install.py for extension /workspace/stable-diffusion-webui-forge/extensions/sd-face-editor.
*** Command: "/opt/environments/python/forge/bin/python" "/workspace/stable-diffusion-webui-forge/extensions/sd-face-editor/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/workspace/stable-diffusion-webui-forge/extensions/sd-face-editor/install.py", line 2, in <module>
***     from face_editor.io.util import load_classes_from_directory
***   File "/workspace/stable-diffusion-webui-forge/extensions/sd-face-editor/face_editor/io/util.py", line 6, in <module>
***     import modules.scripts as scripts
***   File "/workspace/stable-diffusion-webui-forge/modules/scripts.py", line 8, in <module>
***     import gradio as gr
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
***     import gradio.components as components
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
***     from gradio.components.annotated_image import AnnotatedImage
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 13, in <module>
***     from gradio.components.base import IOComponent, _Keywords
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/gradio/components/base.py", line 20, in <module>
***     from fastapi import UploadFile
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
***     from .applications import FastAPI as FastAPI
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/fastapi/applications.py", line 15, in <module>
***     from fastapi import routing
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
***     from fastapi import params
***   File "/opt/environments/python/forge/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
***     from pydantic.fields import FieldInfo, Undefined
*** ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/opt/environments/python/forge/lib/python3.10/site-packages/pydantic/fields.py)` 

And forge does not start.

I tried entering the container and manually removing the extension. But it somehow keeps coming back.

Is there a way to remove this (not yet installed but over and over again trying to install) extension somehow to get forge going again?

Thanks

**Comment by senesees** [comment]
I think some extensions are outdated for the latest forge/gradio

**Comment by gitwittidbit** [comment]
> I think some extensions are outdated for the latest forge/gradio

Any idea how I can disable it or keep forge from trying to install it?

**Comment by senesees** [comment]
Probably deleting extensions/sd-face-editor folder should work

**Comment by gitwittidbit** [comment]
Thank you for the suggestion but as I wrote in my post above, I did try hat and the extension keeps coming back.

Maybe there is a list somewhere of extensions to be installed that keeps bringing it back as long as it is not yet installed. But because it doesn't (fully) install, it keeps coming back?

**Comment by F1zzyD** [comment]
Having this issue as well. I followed the logs that said run "pip install insightface" and now it says:
>ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.94.0 requires pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2, but you have pydantic 2.10.4 which is incompatible.

Seems like this is broken for now
